import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent
sys.path.insert(0, str(PROJECT_ROOT))

from main import RAGSystem
from utils.config import RAGConfig

def run_queries():
    config = RAGConfig(
        pdf_path="data/raw/Horizon_Tours_Complete_Knowledge_Base_2025.pdf",
        use_mock_llm=True,
        embedder_type="local"
    )
    
    # Initialize RAG
    rag = RAGSystem(config)
    
    queries = [
        "What is the price of the Cairo package?",
        "What is the cancellation policy?",
        "What classes are offered by airlines in the travel guide?",
    ]
    
    output_path = PROJECT_ROOT / "query_results.md"
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# RAG System Query Results\n\n")
        f.write("Below are the answers and retrieved source chunks generated by the upgraded RAG system using local sentence-transformer embeddings.\n\n")
        
        for q in queries:
            f.write(f"## Query: {q}\n\n")
            try:
                result = rag.query(q)
                f.write(f"**Answer:**\n{result['answer']}\n\n")
                f.write("### Sources\n")
                for i, source in enumerate(result['sources'], 1):
                    f.write(f"{i}. Page {source['page']}: {source['section']} (Score: {source['score']:.4f})\n")
                f.write(f"\n*Retrieval Time: {result['retrieval_time']:.4f}s*\n\n")
                f.write("---\n\n")
            except Exception as e:
                f.write(f"**Error running query:** {str(e)}\n\n---\n\n")
                
    print(f"Results successfully saved to {output_path}")

if __name__ == "__main__":
    run_queries()
